In [1]:
# Create a model for an HR company that can predict the salary of the employee based
# on his/her years of experience

In [2]:
import pandas as pd
import numpy as np

In [49]:
data = pd.read_csv("Salary_Data.csv")

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes


In [5]:
data.head()

,YearsExperience,Salary
0,1.1,39343.0
1,1.3,46205.0
2,1.5,37731.0
3,2.0,43525.0
4,2.2,39891.0


In [10]:
#Deleting a record based on index (DYnamic)

In [11]:
data.dropna(inplace=True)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 720.0 bytes


In [14]:
# Rules for Regression
# 1. Data must be COMPLETE
# 2. Data must be STRICTLY NUMERIC
# 3. Feature and Label must be represented as 2d np array

In [13]:
#Step1: Seperate data as features and label

features = data.iloc[:,[0]].values
label = data.iloc[:,[1]].values

In [35]:
# Step2: Create Train Test Split

#In sklearn, we have a function named train_test_split()
#
# train_test_split return 4 variables
# X_train ------ training feature set
# X_test ------- testing feature set
# y_train ------ training label set
# y_test ------- testing label set

# training data ---> (X_train, y_train)
# testing data ----> (X_test, y_test)

# Usually train test split ratio --- depends on data size
# 90:10 split --- -small data
# 80:20 split --- standard size
# 65:35 split --- large data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features,
                                                    label,
                                                    test_size=0.2,
                                                    random_state= 10) #Shuffles the data ---- shuffle seed

In [36]:
X_train

array([[ 4.1],
       [ 9.6],
       [ 4. ],
       [ 1.3],
       [ 6. ],
       [ 4.5],
       [ 5.9],
       [ 3. ],
       [ 4. ],
       [ 8.2],
       [ 8.7],
       [10.3],
       [ 7.9],
       [ 3.9],
       [ 9.5],
       [10.5],
       [ 3.2],
       [ 9. ],
       [ 5.1],
       [ 5.3],
       [ 1.1],
       [ 4.9],
       [ 2.2],
       [ 3.7]])

In [37]:
# Step3: Select the ML algo ------ LinearRegression

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train) #Fit() is responsible to find the coeff and intecept


# salary = b0 + b1(yExp)

LinearRegression()

In [38]:
#b0
model.intercept_

array([26089.09663242])

In [39]:
#b1
model.coef_

array([[9356.86299354]])

In [40]:
# salary = 26089 + 9356 (yExp)

In [41]:
model.predict(np.array([[0]]))

array([[26089.09663242]])

In [43]:
#
#
# Check the quality of the model
#
# SL (Significance Level) ---------------------- 0.05
#
# CL = 0.95
#
# Model must achieve atleast 95% score

In [44]:
#
# When it comes to approving a model, always go for generalized model
#
# Generalized Model(Rancho) means the trained model understands the POPULATION'S PATTERN.
# This model not only performs BEST in known data, but also works BEST with unknown data.
#
#
# =========================================================================================
# Guideline by Prashant Nair to identify the generalized model
# =========================================================================================
#
# a. Calc the evaluation score of the model w.r.t training data nad testing data
#
#     trainScore ------- Score generated by Training data
#     testScore -------- Score generated by Testing data
#
# b. Check the below criteria
#
#     if testScore > trainScore and testScore >= CL:
#                   Approve model (Generalized model)
#     else:
#                   Improve the model | Start Optimization Process


In [45]:
trainScore = model.score(X_train,y_train)
testScore = model.score(X_test,y_test)

print(f"Test Score is {testScore} and train score is {trainScore}")

Test Score is 0.9816423482070253 and train score is 0.9494673013344646


In [48]:
# Statistics GOLDEN RULE ---- " The way how you present the data, INFLUENCE the learning power of AI algorithm "

# My own Dr. AI Strange

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

CL = 0.95
win =0

for rs in range(1,101):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LinearRegression()
  model.fit(X_train,y_train)

  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)

  if testScore > trainScore and testScore >=CL:
    win+=1
    print(f"TestScore: {testScore} | trainScore: {trainScore} | rs: {rs}")

print(f"\nTotal Wins : {win} ")

TestScore: 0.9695039421049821 | trainScore: 0.9545249190394051 | rs: 3
TestScore: 0.9631182154839476 | trainScore: 0.9528197369259258 | rs: 8
TestScore: 0.9816423482070253 | trainScore: 0.9494673013344646 | rs: 10
TestScore: 0.9606215790278543 | trainScore: 0.9527636176933665 | rs: 14
TestScore: 0.9835849730044816 | trainScore: 0.9460054870434312 | rs: 26
TestScore: 0.9636425773684423 | trainScore: 0.9527636606684406 | rs: 27
TestScore: 0.9944092048209745 | trainScore: 0.9400496694274887 | rs: 30
TestScore: 0.9778242092591888 | trainScore: 0.9486350116716654 | rs: 37
TestScore: 0.972479448737762 | trainScore: 0.9473317052697812 | rs: 38
TestScore: 0.9928344802911048 | trainScore: 0.9492886917497556 | rs: 39
TestScore: 0.9802519469633169 | trainScore: 0.9491742100347064 | rs: 41
TestScore: 0.9789129767378081 | trainScore: 0.948821675263085 | rs: 46
TestScore: 0.98399193890564 | trainScore: 0.9486450781125914 | rs: 47
TestScore: 0.980277279178695 | trainScore: 0.9500780390200971 | rs: 48

In [52]:
# Deploy Model ----- Help the Dev Team to understand how to use the trained model
#

yExperience = float(input("Enter years of experience: "))

predictedSalary = model.predict(np.array([[yExperience]]))

print(f"Salary for {yExperience} years of experience is ${predictedSalary}")

Enter years of experience: 1.5
Salary for 1.5 years of experience is $[[40860.73970418]]


In [53]:
# Model File
# Pickle package

import pickle
pickle.dump(model, open("SalaryPredictor.pkl","wb"))

In [ ]:
# Dataset: 50_Startups
#
# Goal: Create a model that can predict the profit of the company based on
#       company's spending pattern and company;s location
#
# SL = 0.1
# Deploy the model once created (User Input)